### ISSUE TITLE
where are students working out of?

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/WRDS_intro#1]
Just occurred to me that we want students to be able to access data with `here()` and this implies a project somewhere.

Project setup is part of what you envisioned, and we've been putting data here: https://github.com/richpauloo/wrds. 

Git isn't part of the intro course. Should we have students download from this repo and create a project it it? Do we expect them to create scripts according to some structure?

Related issue: we need access to these data when building the site. Should we just copy the data at the repo above into the `/data` dir in the WRDS_intro project? Is this also where we should save intermediate data that modules depend on?

**Comment by richpauloo** [comment]
That all makes sense @ryanpeek . We can add data to https://github.com/richpauloo/wrds and zip it and send as needed. 

I uploaded Sac data today and preemptively put a dir, `/data/measurements_by_id` full of groundwater stations split by id for the advanced course. 

You mentioned a subdir with spatial and nonspatial data. Feel free to reorganize the wrds data repo. I'm cool with any organization you have in mind. I'll wait to see this before I start building course content so the file paths are consistent. 

Perhaps as you said, data download.file() is used in #5, and then we unzip in R or manually if people have trouble.

For my own dev, I will probably copy data into the `data` folder in the website repo so that my code matches what the students will do assuming they also pull data to a `data` folder in their project repo. Is that alright and will you do the same?

**Comment by ryanpeek** [comment]
@richpauloo, yup that sounds good. I will plan to have a lesson in the beginning (#5) that creates an RStudio project with these folders:

- `data`
- `scripts`
- `output`

I usually have folks add a `figs` folder within output later (during ggplot), and then also strive to keep `data` as the raw versions of everything...so everything in output can be reproduced. 
Thanks for setting this all up! 👍

**Comment by richpauloo** [comment]
I like it. I do the same thing but call scripts "code" and output "results". Names aren't important. Let's stick with yours.

```
data        = raw data
output      = intermediate products like rds files
output/figs = figures like ggplots
scripts     = .R files, ordered by 00_script1.R, 01_script2.R, ... 0n_scriptn.R
```
