### ISSUE TITLE
add stream HUC 12, messy OpenRefine excel sheet, and gauge data to wrds GH repo

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/WRDS_intro#3]
Perhaps just guages in Sac, El Dorado, and Placer counties. Unless this is something you want to pull form CDECRetreive.

**Comment by ryanpeek** [comment]
Already have [messy spreadsheet](https://github.com/ryanpeek/WRDS_intro/blob/main/data/calenviroscreen/ces3results_messy.xlsx), will use API packages to pull gage data. Going to add simplified HUC12 shortly.
